### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ahsanjav** [andreasmang/claire#11]
I am trying to install Claire on ubuntu 20.04 and am unable to compile. 

Error 1: 
petscmat.h:685:1: error: ‘PETSC_CXX_INLINE’ does not name a type; did you mean ‘PETSC_C_INLINE’?
  685 | PETSC_STATIC_INLINE PetscErrorCode MatGetValue(Mat v,PetscInt i,PetscInt j,PetscScalar *va) {return MatGetValues(v,1,&i,1,&j,va);}

Error 2:
./include/MemoryUtils.hpp: In member function ‘PetscErrorCode reg::ManagedMemory<T>::CopyDeviceToHost()’:
./include/MemoryUtils.hpp:260:3: error: ‘PETSC_FUNCTION_NAME_CXX’ was not declared in this scope; did you mean ‘PETSC_FUNCTION_NAME_C’?
  260 |   PetscFunctionBegin;

Has anyone else seen these there is a huge barrage of these errors I just selected one instance. 

Best,
Ahsan

**Comment by andreasmang** [comment]
Can you provide more details? This looks like a compatibility issue. What version of PETSc are you using? Did PETSc compile? Did you use the default configuration for compilation or did you change anything?

**Comment by andreasmang** [comment]
I am closing this.
