### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by NimaMojtahedi** [andreasmang/claire#14]
Dear Claire developers,

Thank you for open sourcing this great package. I would like to ask you, if you have solution to adopt this package to python env. ? 
Second question is related to data size, Is this package able of handling data larger than RAM size? Like data with size of terabyte.

**Comment by andreasmang** [comment]
We are not planning on porting CLAIRE to a Python environment. We have done some preliminary work on wrappers for Python. I have provided some examples of how to use CLAIRE in the documentation.

If you look at our SC papers (links below) you can see that you can process quite large images. The main limitation is the hardware (i.e., memory on individual GPUs or CPU architectures). I believe the largest run we did was for images of size 2048^3. Larger runs are in general possible but would require a larger machine.

1) https://doi.org/10.1145/3126908.3126930
2) https://doi.org/10.1109/SC41405.2020.00042
3) https://doi.org/10.1109/SC.2016.71
