### ISSUE TITLE
broken link in get_libs.sh (cpu banch)

### ISSUE THREAD

**Issue by tjasaki** [andreasmang/claire#7]
The link to the libmorton library is broken (at least in the cpu branch).

#	wget http://users.ices.utexas.edu/~andreas/libs/morton.tar.gz
#  wget http://math.uh.edu/~andreas/libs/morton.tar.gz
	wget https://www.math.uh.edu/~andreas/resources/clairelibs/morton.tar.gz

**Comment by andreasmang** [comment]
@tjasaki Thanks for pointing this out. You are correct. I pushed a fix. This is only relevant for the CPU branch. The external dependency is no longer relevant. CLAIRE compiles without it. If you pull, it should no longer try to grab MORTON.tar.gz.
